export const LOAD_BOOKS = 'LOAD_BOOKS';
export const LOAD_BOOKS_ERROR = 'LOAD_BOOKS_ERROR';
export const CLEAR_BOOKS_ERROR = 'CLEAR_BOOKS_ERROR';
export const LOAD_BOOKS_LOADING = 'LOAD_BOOKS_LOADING';
export const LOAD_BOOK_BY_ID = 'LOAD_BOOK_BY_ID';
export const LOAD_BOOK_BY_ID_LOADING = 'LOAD_BOOK_BY_ID_LOADING';
export const CLEAR_BOOK_SINGLE = 'CLEAR_BOOK_SINGLE';

export const FILTER_BOOKS = 'FILTER_BOOKS';
export const ADD_FILTER_BOOKS_BY_TITLE = 'ADD_FILTER_BOOKS_BY_TITLE';
export const ADD_FILTER_BOOKS_BY_PRICE = 'ADD_FILTER_BOOKS_BY_PRICE';
export const CLEAR_FILTER_BOOKS = 'CLEAR_FILTER_BOOKS';
