export const PURCHASE_SENDING = 'PURCHASE_SENDING';
export const PURCHASE_ERROR = 'PURCHASE_ERROR';
export const CLEAR_PURCHASE_ERROR = 'CLEAR_PURCHASE_ERROR';
export const PURCHASE_SUCCESS = 'PURCHASE_SUCCESS';
export const CLEAR_PURCHASE = 'CLEAR_PURCHASE';
