export const AUTH_USER = 'AUTH_USER';
export const AUTH_USER_ERROR = 'AUTH_USER_ERROR';
export const CLEAR_USER_ERROR = 'CLEAR_USER_ERROR';
export const AUTH_USER_LOADING = 'AUTH_USER_LOADING';
export const CLEAR_USER = 'CLEAR_USER';
